changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: "New Features"
      labels:
        - enhancement
        - feature
    - title: "Bug Fixes"
      labels:
        - bug
        - fix
    - title: "Breaking Changes"
      labels:
        - breaking-change
    - title: "Other Changes"
      labels:
        - "*"
